name=TFT_SPI
version=0.0.1
author=Tuya
maintainer=Tuya
sentence=Supports TFT SPI display on arduino.
paragraph=Supports TFT SPI display on arduino.
category=Display
url=https://github.com/tuya/arduino-tuyaopen
architectures=*
includes=TFT_SPI.h
